image: alpine/edge
packages:
  - ruby-dev
  - nodejs
environment:
  repo: newbarn 
sources:
  - https://git.sr.ht/~stfn/newbarn
secrets:
  - d1a8c6e8-f481-4e50-9ec8-f780651ea483 # neocities
tasks:
  - setup: |
      sudo gem install --no-document bundler neocities
  - build: |
      cd $repo
      sh ./build-jekyll
  - deploy: |
      cd $repo
      sh ./deploy-neocities $repo _site
