image: alpine/edge
packages:
  - ruby-dev
  - nodejs
  - npm
  - build-base
  - libffi-dev
environment:
  repo: newbarn
sources:
  - https://git.sr.ht/~stfn/newbarn
secrets:
  - d1a8c6e8-f481-4e50-9ec8-f780651ea483 # neocities
tasks:
  - build: |
      cd $repo
      bundle exec jekyll build
      html-minifier --input-dir _site --output-dir _site --collapse-whitespace --file-ext html
      set +x
      export NEOCITIES_API_KEY=$(cat /home/build/.neocities/$repo)
      set -x
      neocities push --prune _site
